spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: user
    password: 1234
    driver-class-name: org.postgresql.Driver
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  sql:
    init:
      platform: postgres